// <auto-generated />
namespace MiniSocialNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:MiniSocialNetwork/Migrations/202012181602158_Initial.Designer.cs
            get { return "202012181602158_Initial"; }
=======
            get { return "202012161615023_Initial"; }
>>>>>>> master:MiniSocialNetwork/Migrations/202012161615023_Initial.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
